### ISSUE TITLE
Unsupported operation: BIND

### ISSUE THREAD

**Issue by Rintarou** [Callidon/sage-client#1]
When running any query from the
[bind/](https://www.w3.org/2009/sparql/docs/tests/summary.html#bind-bind01) folder, or the [entailment/bind](https://www.w3.org/2009/sparql/docs/tests/summary.html#entailment-bind01)
of the [w3c SPARQL 1.1 compliance benchmark](https://www.w3.org/2009/sparql/implementations/)

We obtain the following output
```
UnsupportedQueryError: The query is not yet supported
Unsupported group type: bind
    at new SparqlIterator (/home/runner/Documents/M1_ALMA/Stage/SaGe/sage-client/src/sparql-iterator.js:140:13)
    at Object.<anonymous> (/home/runner/Documents/M1_ALMA/Stage/SaGe/sage-client/bin/sage-client.js:78:44)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:660:3
```

Queries have the following form:
```sparql
PREFIX : <http://example.org/> 

SELECT *
{
  ?s ?p ?o .
  BIND(?nova AS ?z)
}
```

The query is simply unsupported by the current engine version.
it represents 18 queries from the w3c benchmark, so it is rather relevant.

**Comment by Slaanaroth** [comment]
Bind is supported, some weird scope errors may remain
