### ISSUE TITLE
Unsupported operations: functions folder

### ISSUE THREAD

**Issue by Rintarou** [Callidon/sage-client#3]
When running nearly any query from the
[functions/](https://www.w3.org/2009/sparql/docs/tests/summary.html#functions-abs01) folder,
of the [w3c SPARQL 1.1 compliance benchmark](https://www.w3.org/2009/sparql/implementations/)

We either get an error of the following kind:
```
UnsupportedQueryError: The query is not yet supported
Unsupported operator: abs.
    at new SparqlIterator (/home/runner/Documents/M1_ALMA/Stage/SaGe/sage-client/src/sparql-iterator.js:144:13)
    at Object.<anonymous> (/home/runner/Documents/M1_ALMA/Stage/SaGe/sage-client/bin/sage-client.js:78:44)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:660:3
```

or an empty xml response:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<sparql xlmns="http://www.w3.org/2005/sparql-results#">
  <head>
    <variable name="s"/>
    <variable name="str1"/>
  </head>
  <results>
    <result>
      <binding name="s">
        <uri/>
      </binding>
      <binding name="str1">
        <uri/>
      </binding>
    </result>
</results>
</sparql>
```

Most of the functions and filters are yet to be implementend. they represent 61 requests total, and only 5 of them pass currently (in, notin, contains).
It is desirable to implement them at some point.
Altough this is a single issue, each query is independant from the other, so this is a case by case implementation problem.

**Comment by Rintarou** [comment]
A lot of functions have been implemented out, only a few still have errors passing, but due to number representation or variable output order (i.e: getting s,o,p, instead of s,p,o)

Please refer to the [sage-benchmark](https://github.com/Rintarou/sage-benchmark) for additionnal information on remaining issues on these
